<template>
  <main class="insight-page">
    <header class="insight-nav"><button class="insight-brand" type="button" @click="router.push('/system/user')"><span class="brand-mark"><i /><i /><i /></span><b class="brand-word">Sentiment</b></button><div class="mode-switch"><button :class="{ active: activeTab === 'chat' }" type="button" @click="activeTab = 'chat'">聊天</button><button :class="{ active: activeTab === 'work' }" type="button" @click="activeTab = 'work'">工作</button></div><button class="exit-button" type="button" @click="logout">退出登录</button></header>
    <section v-if="activeTab === 'chat'" class="chat-workspace"><div class="chat-intro"><span class="insight-kicker">SENTIMENT COPILOT · 预留模型接口</span><h1>{{ submitted ? '这份感受，值得被看见' : '准备好了，随时开始' }}</h1><p>{{ submitted ? '模型分析结果将在这里呈现。' : '把用户的真实反馈交给我，开始一次情绪探索。' }}</p></div><div v-if="result" class="result-card"><div><span class="result-label">情绪倾向</span><strong>{{ result.sentiment === 'positive' ? '正向' : result.sentiment === 'negative' ? '负向' : '中性' }}</strong></div><div><span class="result-label">置信度</span><strong>{{ result.score }}%</strong></div><p>{{ result.summary }}</p><div class="keyword-row"><span v-for="word in result.keywords" :key="word">{{ word }}</span></div></div><form class="chat-composer" @submit.prevent="submitMessage"><button class="plus-button" type="button" aria-label="添加商品信息" @click="showProductModal = true">＋</button><input v-model="message" :placeholder="language === 'zh' ? '问问用户的真实感受' : 'Ask about your users’ real feelings'" :disabled="loading" /><button class="language-button" type="button" :aria-label="language === 'zh' ? '切换英文' : '切换中文'" @click="toggleLanguage">{{ language === 'zh' ? '中' : 'EN' }}<span>⌄</span></button><button class="send-button" type="submit" :disabled="loading">{{ loading ? '…' : '↑' }}</button></form><p class="api-hint">{{ apiMessage }}</p></section>
    <section v-else class="work-panel"><span class="insight-kicker">WORKSPACE</span><h1>把洞察变成下一步行动。</h1><p>这里会承载后续的产品分析工作流。</p><button class="back-action" type="button" @click="activeTab = 'chat'">回到聊天 <span>→</span></button></section>
    <div v-if="showProductModal" class="modal-mask" @click.self="showProductModal = false"><form class="product-modal" @submit.prevent="saveProduct"><button class="modal-close" type="button" @click="showProductModal = false">×</button><span class="insight-kicker">PRODUCT CONTEXT</span><h2>补充商品信息</h2><p>让未来的模型更了解这次反馈属于谁。</p><label>商品名称<input v-model="product.name" required placeholder="例如：澄见智能水杯" /></label><label>商品类别<select v-model="product.category"><option value="">请选择商品类别</option><option>电子产品</option><option>生活用品</option><option>美妆个护</option><option>其他</option></select></label><label>用户评价<input v-model="product.rating" placeholder="例如：4.5 / 5" /></label><label>备注<textarea v-model="product.note" rows="3" placeholder="补充更多背景信息" /></label><button class="save-product" type="submit">保存并继续 <span>→</span></button></form></div>
  </main>
</template>
<script lang="ts" setup>
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  import { predictSentiment, saveProductDraft, type ProductDraft, type SentimentPredictResult } from '/@/api/sentiment';
  import { useUserStore } from '/@/store/modules/user';
  const router = useRouter(); const userStore = useUserStore();
  const activeTab = ref<'chat' | 'work'>('chat'); const language = ref<'zh' | 'en'>('zh'); const message = ref(''); const loading = ref(false); const submitted = ref(false); const showProductModal = ref(false); const apiMessage = ref('输入内容后将调用情绪模型接口，当前接口尚未接入模型。'); const result = ref<SentimentPredictResult | null>(null);
  const product = ref<ProductDraft>({ name: '', category: '', rating: '', note: '' });
  function toggleLanguage() { language.value = language.value === 'zh' ? 'en' : 'zh'; apiMessage.value = language.value === 'zh' ? '已切换为中文输入' : 'Switched to English input'; }
  async function submitMessage() { if (!message.value.trim()) { apiMessage.value = language.value === 'zh' ? '先输入一段用户反馈，再发送给模型。' : 'Enter some user feedback before sending.'; return; } loading.value = true; submitted.value = true; apiMessage.value = '正在等待模型返回分析结果…'; try { result.value = await predictSentiment({ content: message.value, product: product.value.name ? product.value : undefined }); apiMessage.value = '分析完成，结果由模型接口返回。'; } catch { apiMessage.value = '模型接口暂未接入，已保留本次输入。'; result.value = { sentiment: 'neutral', score: 0, summary: '当前为前端壳子，连接模型服务后会在此展示真实分析结果。', keywords: ['等待模型', '接口预留'] }; } finally { loading.value = false; } }
  async function saveProduct() { try { await saveProductDraft(product.value); apiMessage.value = '商品信息已保存，后续预测将带上这份上下文。'; } catch { apiMessage.value = '商品信息已在当前页面保留，数据库接口待接入。'; } showProductModal.value = false; }
  async function logout() { await userStore.logout(true); }
</script>
<style lang="less" scoped>
  .brand-word { color: #214d58; font-size: 22px; font-weight: 600; line-height: .9; letter-spacing: -.085em; }
  .insight-page { min-height: 100dvh; color: #214d58; background: radial-gradient(circle at 82% 0, #dbf7f2, transparent 33rem), #f7fcfb; } .insight-nav { position: sticky; top: 0; z-index: 3; display: flex; align-items: center; justify-content: space-between; height: 78px; padding: 0 clamp(22px, 6vw, 90px); border-bottom: 1px solid rgba(46,115,126,.12); background: rgba(247,252,251,.8); backdrop-filter: blur(20px); } .insight-brand { display: flex; align-items: center; gap: 10px; border: 0; color: #214d58; background: transparent; cursor: pointer; } .brand-mark { position: relative; display: inline-block; width: 31px; height: 31px; border-radius: 12px 12px 12px 3px; background: linear-gradient(135deg,#1aa2a3,#82d9c2); } .brand-mark i { position: absolute; border: 2px solid #f1fffb; border-radius: 2px; } .brand-mark i:nth-child(1){top:7px;left:6px;width:11px;height:9px;border-right:0}.brand-mark i:nth-child(2){top:11px;left:13px;width:12px;height:8px;border-left:0;border-bottom:0;transform:skewX(-25deg)}.brand-mark i:nth-child(3){right:4px;bottom:7px;width:11px;height:6px;border-left:0;border-top:0}.insight-brand small { display: block; color: #8badb0; font-size: 7px; letter-spacing: .24em; text-align: left; } .mode-switch { display: flex; padding: 3px; border-radius: 999px; background: #edf4f2; box-shadow: inset 0 1px 2px rgba(66,130,132,.06); } .mode-switch button { min-width: 90px; height: 42px; border: 0; border-radius: 999px; color: #749297; background: transparent; cursor: pointer; font-size: 16px; } .mode-switch .active { color: #244f58; background: #fff; box-shadow: 0 5px 15px rgba(72,129,132,.12); } .exit-button { border: 0; color: #5d878a; background: transparent; cursor: pointer; font-size: 13px; font-weight: 700; }
  .chat-workspace { display: flex; min-height: calc(100dvh - 78px); flex-direction: column; align-items: center; justify-content: center; padding: 60px 22px 100px; } .chat-intro { text-align: center; } .insight-kicker { display: inline-flex; margin-bottom: 18px; color: #69a29e; font-size: 10px; font-weight: 800; letter-spacing: .18em; } .chat-intro h1, .work-panel h1 { margin: 0; color: #214d58; font-size: clamp(32px, 4vw, 52px); font-weight: 600; letter-spacing: -.07em; } .chat-intro p, .work-panel p { margin: 17px 0 0; color: #8ba5a6; font-size: 13px; } .chat-composer { display: flex; align-items: center; width: min(1150px, 100%); min-height: 76px; margin-top: 74px; padding: 9px 12px 9px 14px; border: 1px solid rgba(56,125,131,.13); border-radius: 22px; background: rgba(255,255,255,.82); box-shadow: 0 18px 45px rgba(76,147,144,.1); } .chat-composer input { flex: 1; min-width: 0; height: 52px; border: 0; outline: 0; color: #214d58; background: transparent; font-size: 16px; } .plus-button, .language-button, .send-button { border: 0; cursor: pointer; } .plus-button { width: 46px; height: 46px; border-radius: 14px; color: #368a87; background: #e1f5ef; font-size: 29px; font-weight: 300; line-height: 1; } .language-button { margin-right: 8px; color: #759397; background: transparent; font-size: 13px; } .send-button { width: 46px; height: 46px; border-radius: 50%; color: #effffc; background: #107f87; box-shadow: 0 7px 16px rgba(16,127,135,.2); font-size: 22px; } .send-button:disabled { cursor: not-allowed; opacity: .42; } .api-hint { margin-top: 14px; color: #9ab1b1; font-size: 11px; } .result-card { width: min(700px, 100%); margin-top: 35px; padding: 25px; border: 1px solid rgba(56,125,131,.12); border-radius: 22px; background: rgba(255,255,255,.7); box-shadow: 0 15px 35px rgba(76,147,144,.08); } .result-card > div { display: inline-flex; min-width: 130px; flex-direction: column; gap: 7px; margin-right: 28px; } .result-label { color: #8ba5a6; font-size: 11px; } .result-card strong { color: #238d89; font-size: 24px; } .result-card p { margin: 18px 0; color: #557d83; font-size: 13px; line-height: 1.7; } .keyword-row { display: flex; gap: 8px; } .keyword-row span { padding: 6px 10px; border-radius: 999px; color: #4d8c88; background: #e7f6f0; font-size: 11px; } .work-panel { display: grid; min-height: calc(100dvh - 78px); place-content: center; padding: 40px 22px; text-align: center; } .back-action { margin: 35px auto 0; padding: 13px 20px; border: 0; border-radius: 13px; color: #f2fffc; background: #167f87; cursor: pointer; }
  .modal-mask { position: fixed; inset: 0; z-index: 10; display: grid; place-items: center; padding: 22px; background: rgba(31,77,84,.22); backdrop-filter: blur(8px); } .product-modal { position: relative; width: min(490px, 100%); padding: 31px; border: 1px solid rgba(255,255,255,.75); border-radius: 26px; background: rgba(250,255,253,.94); box-shadow: 0 25px 70px rgba(52,115,117,.19); } .modal-close { position: absolute; top: 17px; right: 18px; border: 0; color: #7e9b9d; background: transparent; cursor: pointer; font-size: 25px; } .product-modal h2 { margin: 0; color: #285963; font-size: 25px; letter-spacing: -.06em; } .product-modal p { margin: 8px 0 24px; color: #8aa3a4; font-size: 12px; } .product-modal label { display: block; margin-top: 14px; color: #60878a; font-size: 11px; } .product-modal input, .product-modal select, .product-modal textarea { display: block; width: 100%; margin-top: 7px; padding: 0 13px; border: 1px solid rgba(56,125,131,.15); border-radius: 12px; outline: none; color: #285963; background: rgba(255,255,255,.76); font: inherit; font-size: 13px; } .product-modal input, .product-modal select { height: 43px; } .product-modal textarea { padding-top: 11px; resize: vertical; } .product-modal input:focus, .product-modal select:focus, .product-modal textarea:focus { border-color: #55b6a7; box-shadow: 0 0 0 3px rgba(85,182,167,.12); } .save-product { width: 100%; height: 45px; margin-top: 23px; border: 0; border-radius: 13px; color: #effffc; background: #167f87; cursor: pointer; font-size: 13px; font-weight: 700; }
  @media(max-width:600px){.insight-nav{padding:0 18px}.mode-switch button{min-width:62px;font-size:13px}.exit-button{font-size:11px}.insight-brand b{font-size:13px}.chat-workspace{padding-top:35px}.chat-composer{min-height:64px;border-radius:18px}.chat-composer input{height:42px;font-size:14px}.plus-button,.send-button{width:40px;height:40px}.language-button{display:none}.product-modal{padding:25px 20px}}
  @media(prefers-reduced-motion:reduce){.insight-page *{scroll-behavior:auto!important;transition-duration:.01ms!important}}
</style>
