import { motion } from 'framer-motion';
import { ArrowRight, Check, Play, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ActionButton } from '../components/ActionButton';
import { Footer } from '../components/Footer';
import { HeroVisual } from '../components/HeroVisual';
import { InsightCard } from '../components/InsightCard';
import { Navbar } from '../components/Navbar';
import { getInsights, type Insight } from '../services/backendService';

export function Home() { const [insights, setInsights] = useState<Insight[]>([]); useEffect(() => { getInsights().then(setInsights); }, []); return <div className="page-shell"><Navbar /><main><section className="hero-section"><div className="hero-copy"><motion.div className="eyebrow" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><span className="eyebrow-dot" /> 产品情绪洞察平台</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }}>看见用户的<br /><em>真实感受。</em></motion.h1><motion.p className="hero-description" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .18 }}>从海量反馈中，捕捉情绪的方向与温度。<br />让每一次产品决策，都更接近用户心里的答案。</motion.p><motion.div className="hero-actions" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .28 }}><Link to="/dashboard"><ActionButton>进入我的空间 <ArrowRight size={17} /></ActionButton></Link><Link to="/explore"><ActionButton variant="secondary"><span className="play-button"><Play size={12} fill="currentColor" /></span> 看看它如何工作</ActionButton></Link></motion.div><div className="hero-proof"><div className="proof-avatars"><span>J</span><span>L</span><span>Y</span><span>+</span></div><span>被 2,000+ 个团队<br />用来听见用户</span><ShieldCheck size={17} /></div></div><HeroVisual /></section><section className="signal-strip"><span className="signal-title">你的产品，正在被这样感受</span><div className="signal-items"><span><i /> 体验更顺滑</span><span><i /> 值得被推荐</span><span><i /> 还可以更贴心</span><span><i /> 我们听见了</span></div></section><section className="insights-section"><div className="section-intro"><div><span className="section-kicker">从反馈，到洞察</span><h2>把分散的声音，<br /><span>汇成清晰的方向。</span></h2></div><p>不止告诉你发生了什么，<br />也帮你理解为什么，以及下一步。</p></div><div className="insight-grid">{insights.map((insight, index) => <InsightCard key={insight.id} insight={insight} index={index} />)}</div></section><section className="quiet-cta"><div><span className="section-kicker">准备好了吗</span><h2>从今天开始，<br /><em>听见更多可能。</em></h2></div><Link to="/dashboard"><ActionButton>开始探索 <ArrowRight size={17} /></ActionButton></Link><div className="quiet-checks"><span><Check size={14} /> 无需信用卡</span><span><Check size={14} /> 5 分钟上手</span></div></section></main><Footer /></div>; }
